---
driver:
  name: vagrant
  network:
  - ["private_network", { type: "dhcp" }]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    driver:
      box: mesosphere/dcos-centos-virtualbox
      box_url: https://downloads.dcos.io/dcos-vagrant/metadata.json

suites:

  - name: bootstrap
    provisioner:
      name: nodes
    driver:
      customize:
        memory: 1024
      network:
        - ["private_network", {ip: "192.168.33.110"}]
    run_list:
      - recipe[mesosphere_dcos::bootstrap]
    attributes:
      dcos:
        installer:
          url: https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh
        bootstrap:
          port: 8080
        cluster:
          masters: 'ipaddress:192.168.33.111'
        docker:
          args: '--raw-logs --log-opt=labels=a,b'
        #customerKey: enterprise-version only
        superuser:
          name: test
          password: test

  - name: master
    provisioner:
      name: nodes
    driver:
      customize:
        memory: 1024
      network:
        - ["private_network", {ip: "192.168.33.111"}]
        - ["forwarded_port", {guest: 80, host: 8082}]
    run_list:
      - recipe[mesosphere_dcos::master]
    attributes:
      dcos:
        bootstrap:
          host: 192.168.33.110
          port: 8080

  - name: agent
    driver:
      network:
        - ["private_network", {ip: "192.168.33.113"}]
    run_list:
      - recipe[mesosphere_dcos::agent]
    attributes:
      dcos:
        bootstrap:
          host: 192.168.33.110
          port: 8080

  - name: public
    driver:
      network:
        - ["private_network", {ip: "192.168.33.114"}]
        - ["forwarded_port", {guest: 80, host: 8081}]
    run_list:
      - recipe[mesosphere_dcos::public]
    attributes:
      dcos:
        bootstrap:
          host: 192.168.33.110
          port: 8080
